hourOfCode.agentAnalyze(SixDirection.Forward);
hourOfCode.agentDetectDryFern(SixDirection.Forward);
hourOfCode.agentDetectDryGrass(SixDirection.Forward);
hourOfCode.agentDetectDryBrush(SixDirection.Forward);
hourOfCode.hazardsRemainL4();
hourOfCode.hazardsRemainL5();
hourOfCode.hazardsRemainL6();
hourOfCode.agentDestroyL4(SixDirection.Forward);
hourOfCode.agentDestroyL5(SixDirection.Forward);
hourOfCode.agentDestroyL6(SixDirection.Forward);
hourOfCode.openDoor();
hourOfCode.completeTask();
hourOfCode.agentLookForHazards();
hourOfCode.agentSeeHazard();
hourOfCode.alertTeam();
hourOfCode.fakePlace(Block.Grass, SixDirection.Forward);
