hourOfCode.analyze(SixDirection.Forward);
hourOfCode.agentDetectDeadBush(SixDirection.Forward);
hourOfCode.agentDetectDryGrass(SixDirection.Forward);
hourOfCode.hazardsRemainL4();
hourOfCode.hazardsRemainL5();
hourOfCode.hazardsRemainL6();
hourOfCode.agentDestroyL4(SixDirection.Forward);
hourOfCode.agentDestroyL5(SixDirection.Forward);
hourOfCode.agentDestroyL6(SixDirection.Forward);
